package com.utils.map;
// Generated 30 Dec, 2016 1:24:09 PM by Hibernate Tools 3.6.0



/**
 * Bloodgroupmaster generated by hbm2java
 */
public class Bloodgroupmaster  implements java.io.Serializable {


     private String id;
     private String bloodgroup;

    public Bloodgroupmaster() {
    }

	
    public Bloodgroupmaster(String id) {
        this.id = id;
    }
    public Bloodgroupmaster(String id, String bloodgroup) {
       this.id = id;
       this.bloodgroup = bloodgroup;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getBloodgroup() {
        return this.bloodgroup;
    }
    
    public void setBloodgroup(String bloodgroup) {
        this.bloodgroup = bloodgroup;
    }




}


