package com.utils.map;
// Generated 30 Dec, 2016 1:24:09 PM by Hibernate Tools 3.6.0



/**
 * Castemaster generated by hbm2java
 */
public class Castemaster  implements java.io.Serializable {


     private String id;
     private String caste;

    public Castemaster() {
    }

	
    public Castemaster(String id) {
        this.id = id;
    }
    public Castemaster(String id, String caste) {
       this.id = id;
       this.caste = caste;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCaste() {
        return this.caste;
    }
    
    public void setCaste(String caste) {
        this.caste = caste;
    }




}


