package com.utils.map;
// Generated 30 Dec, 2016 1:24:09 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Coursemaster generated by hbm2java
 */
public class Coursemaster  implements java.io.Serializable {


     private String id;
     private String coursetypeid;
     private String coursename;
     private String noOfSemester;
     private String collegeid;
     private String academicYear;
     private Date effectiveDate;
     private String enteredby;
     private Date entereddt;

    public Coursemaster() {
    }

	
    public Coursemaster(String id) {
        this.id = id;
    }
    public Coursemaster(String id, String coursetypeid, String coursename, String noOfSemester, String collegeid, String academicYear, Date effectiveDate, String enteredby, Date entereddt) {
       this.id = id;
       this.coursetypeid = coursetypeid;
       this.coursename = coursename;
       this.noOfSemester = noOfSemester;
       this.collegeid = collegeid;
       this.academicYear = academicYear;
       this.effectiveDate = effectiveDate;
       this.enteredby = enteredby;
       this.entereddt = entereddt;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCoursetypeid() {
        return this.coursetypeid;
    }
    
    public void setCoursetypeid(String coursetypeid) {
        this.coursetypeid = coursetypeid;
    }
    public String getCoursename() {
        return this.coursename;
    }
    
    public void setCoursename(String coursename) {
        this.coursename = coursename;
    }
    public String getNoOfSemester() {
        return this.noOfSemester;
    }
    
    public void setNoOfSemester(String noOfSemester) {
        this.noOfSemester = noOfSemester;
    }
    public String getCollegeid() {
        return this.collegeid;
    }
    
    public void setCollegeid(String collegeid) {
        this.collegeid = collegeid;
    }
    public String getAcademicYear() {
        return this.academicYear;
    }
    
    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }
    public Date getEffectiveDate() {
        return this.effectiveDate;
    }
    
    public void setEffectiveDate(Date effectiveDate) {
        this.effectiveDate = effectiveDate;
    }
    public String getEnteredby() {
        return this.enteredby;
    }
    
    public void setEnteredby(String enteredby) {
        this.enteredby = enteredby;
    }
    public Date getEntereddt() {
        return this.entereddt;
    }
    
    public void setEntereddt(Date entereddt) {
        this.entereddt = entereddt;
    }




}


