package com.utils.map;
// Generated 30 Dec, 2016 1:24:09 PM by Hibernate Tools 3.6.0



/**
 * Religionmaster generated by hbm2java
 */
public class Religionmaster  implements java.io.Serializable {


     private String id;
     private String religion;

    public Religionmaster() {
    }

	
    public Religionmaster(String id) {
        this.id = id;
    }
    public Religionmaster(String id, String religion) {
       this.id = id;
       this.religion = religion;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getReligion() {
        return this.religion;
    }
    
    public void setReligion(String religion) {
        this.religion = religion;
    }




}


