package com.utils.map;
// Generated 4 Jan, 2017 3:34:13 PM by Hibernate Tools 3.6.0

import java.sql.Blob;
import java.util.Date;

/**
 * Staffmaster generated by hbm2java
 */
public class Staffmaster implements java.io.Serializable {

    private long id;
    private String staffid;
    private String title;
    private String firstname;
    private String lastname;
    private Character sex;
    private String stafftype;
    private Character empStatus;
    private Character maritalStatus;
    private String departmentid;
    private String subDept;
    private String desig;
    private String bloodgroup;
    private Date dateofbirth;
    private Date dateofjoin;
    private String qualification;
    private String experiance;
    private String guardian;
    private String mobile;
    private String resino;
    private String email;
    private String accountno;
    private String bankid;
    private String bankname;
    private String pfno;
    private String esino;
    private String panno;
    private Character active;
    private String houseNoName;
    private String post;
    private String city;
    private String distid;
    private String stateid;
    private String countryid;
    private String pin;
    private Character tutor;
    private String teachexp;
    private String nonteachexp;
    private String age;
    private Date confirmdate;
    private Character approve;
    private Character dutyRequired;
    private Character punchingrequired;
    private String uanNo;
    private String careOf;
    private String electionId;
    private String uan;
    private String aadharno;
    private byte[] image;
    private Character resigned;
    private Character verified;
    private String referencestaffid;
    private Character stipend;
    private Character visiting;
    private Character inchargeDept;
    private String collegeid;
    private String academicYear;
    private String enteredby;
    private Date entereddate;
    private String lastModifiedBy;
    private Date lastModifiedDate;
    private String caste;
    private String castename;
    private String religion;
    private String handicap;
     private String permHouseNoName;
     private String permPost;
     private String permCity;
     private String permDistid;
     private String permStateid;
     private String permCountryid;
     private String permEmail;
     private String permPin;
     private Character hod;
    public Staffmaster() {
    }

    public Staffmaster(long id, String staffid) {
        this.id = id;
        this.staffid = staffid;
    }

    public Staffmaster(String staffid, String title, String firstname, String lastname, Character sex, String stafftype, Character empStatus, Character maritalStatus, String departmentid, String subDept, String desig, String bloodgroup, Date dateofbirth, Date dateofjoin, String qualification, String experiance, String guardian, String mobile, String resino, String email, String accountno, String bankid, String bankname, String pfno, String esino, String panno, Character active, String houseNoName, String post, String city, String distid, String stateid, String countryid, String pin, Character tutor, String teachexp, String nonteachexp, String age, Date confirmdate, Character approve, Character dutyRequired, Character punchingrequired, String uanNo, String careOf, String electionId, String uan, String aadharno, byte[] image, Character resigned, Character verified, String referencestaffid, Character stipend, Character visiting, Character inchargeDept, String collegeid, String academicYear, String enteredby, String lastModifiedBy, Date lastModifiedDate, String caste, String castename, String religion, String handicap, String permHouseNoName, String permPost, String permCity, String permDistid, String permStateid, String permCountryid, String permEmail, String permPin,Character hod) {
        //this.id = id;
        this.staffid = staffid;
        this.title = title;
        this.firstname = firstname;
        this.lastname = lastname;
        this.sex = sex;
        this.stafftype = stafftype;
        this.empStatus = empStatus;
        this.maritalStatus = maritalStatus;
        this.departmentid = departmentid;
        this.subDept = subDept;
        this.desig = desig;
        this.bloodgroup = bloodgroup;
        this.dateofbirth = dateofbirth;
        this.dateofjoin = dateofjoin;
        this.qualification = qualification;
        this.experiance = experiance;
        this.guardian = guardian;
        this.mobile = mobile;
        this.resino = resino;
        this.email = email;
        this.accountno = accountno;
        this.bankid = bankid;
        this.bankname = bankname;
        this.pfno = pfno;
        this.esino = esino;
        this.panno = panno;
        this.active = active;
        this.houseNoName = houseNoName;
        this.post = post;
        this.city = city;
        this.distid = distid;
        this.stateid = stateid;
        this.countryid = countryid;
        this.pin = pin;
        this.tutor = tutor;
        this.teachexp = teachexp;
        this.nonteachexp = nonteachexp;
        this.age = age;
        this.confirmdate = confirmdate;
        this.approve = approve;
        this.dutyRequired = dutyRequired;
        this.punchingrequired = punchingrequired;
        this.uanNo = uanNo;
        this.careOf = careOf;
        this.electionId = electionId;
        this.uan = uan;
        this.aadharno = aadharno;
        this.image = image;
        this.resigned = resigned;
        this.verified = verified;
        this.referencestaffid = referencestaffid;
        this.stipend = stipend;
        this.visiting = visiting;
        this.inchargeDept = inchargeDept;
        this.collegeid = collegeid;
        this.academicYear = academicYear;
        this.enteredby = enteredby;
        //this.entereddate = entereddate;
        this.lastModifiedBy = lastModifiedBy;
        this.lastModifiedDate = lastModifiedDate;
        this.caste = caste;
       this.castename = castename;
       this.religion = religion;
       this.handicap = handicap;
       this.permHouseNoName = permHouseNoName;
       this.permPost = permPost;
       this.permCity = permCity;
       this.permDistid = permDistid;
       this.permStateid = permStateid;
       this.permCountryid = permCountryid;
       this.permEmail = permEmail;
       this.permPin = permPin;
       this.hod= hod;
    }

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getStaffid() {
        return this.staffid;
    }

    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }

    public String getTitle() {
        return this.title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getFirstname() {
        return this.firstname;
    }

    public void setFirstname(String firstname) {
        this.firstname = firstname;
    }

    public String getLastname() {
        return this.lastname;
    }

    public void setLastname(String lastname) {
        this.lastname = lastname;
    }

    public Character getSex() {
        return this.sex;
    }

    public void setSex(Character sex) {
        this.sex = sex;
    }

    public String getStafftype() {
        return this.stafftype;
    }

    public void setStafftype(String stafftype) {
        this.stafftype = stafftype;
    }

    public Character getEmpStatus() {
        return this.empStatus;
    }

    public void setEmpStatus(Character empStatus) {
        this.empStatus = empStatus;
    }

    public Character getMaritalStatus() {
        return this.maritalStatus;
    }

    public void setMaritalStatus(Character maritalStatus) {
        this.maritalStatus = maritalStatus;
    }

    public String getDepartmentid() {
        return this.departmentid;
    }

    public void setDepartmentid(String departmentid) {
        this.departmentid = departmentid;
    }

    public String getSubDept() {
        return this.subDept;
    }

    public void setSubDept(String subDept) {
        this.subDept = subDept;
    }

    public String getDesig() {
        return this.desig;
    }

    public void setDesig(String desig) {
        this.desig = desig;
    }

    public String getBloodgroup() {
        return this.bloodgroup;
    }

    public void setBloodgroup(String bloodgroup) {
        this.bloodgroup = bloodgroup;
    }

    public Date getDateofbirth() {
        return this.dateofbirth;
    }

    public void setDateofbirth(Date dateofbirth) {
        this.dateofbirth = dateofbirth;
    }

    public Date getDateofjoin() {
        return this.dateofjoin;
    }

    public void setDateofjoin(Date dateofjoin) {
        this.dateofjoin = dateofjoin;
    }

    public String getQualification() {
        return this.qualification;
    }

    public void setQualification(String qualification) {
        this.qualification = qualification;
    }

    public String getExperiance() {
        return this.experiance;
    }

    public void setExperiance(String experiance) {
        this.experiance = experiance;
    }

    public String getGuardian() {
        return this.guardian;
    }

    public void setGuardian(String guardian) {
        this.guardian = guardian;
    }

    public String getMobile() {
        return this.mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public String getResino() {
        return this.resino;
    }

    public void setResino(String resino) {
        this.resino = resino;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getAccountno() {
        return this.accountno;
    }

    public void setAccountno(String accountno) {
        this.accountno = accountno;
    }

    public String getBankid() {
        return this.bankid;
    }

    public void setBankid(String bankid) {
        this.bankid = bankid;
    }

    public String getBankname() {
        return this.bankname;
    }

    public void setBankname(String bankname) {
        this.bankname = bankname;
    }

    public String getPfno() {
        return this.pfno;
    }

    public void setPfno(String pfno) {
        this.pfno = pfno;
    }

    public String getEsino() {
        return this.esino;
    }

    public void setEsino(String esino) {
        this.esino = esino;
    }

    public String getPanno() {
        return this.panno;
    }

    public void setPanno(String panno) {
        this.panno = panno;
    }

    public Character getActive() {
        return this.active;
    }

    public void setActive(Character active) {
        this.active = active;
    }

    public String getHouseNoName() {
        return this.houseNoName;
    }

    public void setHouseNoName(String houseNoName) {
        this.houseNoName = houseNoName;
    }

    public String getPost() {
        return this.post;
    }

    public void setPost(String post) {
        this.post = post;
    }

    public String getCity() {
        return this.city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getDistid() {
        return this.distid;
    }

    public void setDistid(String distid) {
        this.distid = distid;
    }

    public String getStateid() {
        return this.stateid;
    }

    public void setStateid(String stateid) {
        this.stateid = stateid;
    }

    public String getCountryid() {
        return this.countryid;
    }

    public void setCountryid(String countryid) {
        this.countryid = countryid;
    }

    public String getPin() {
        return this.pin;
    }

    public void setPin(String pin) {
        this.pin = pin;
    }

    public Character getTutor() {
        return this.tutor;
    }

    public void setTutor(Character tutor) {
        this.tutor = tutor;
    }

    public String getTeachexp() {
        return this.teachexp;
    }

    public void setTeachexp(String teachexp) {
        this.teachexp = teachexp;
    }

    public String getNonteachexp() {
        return this.nonteachexp;
    }

    public void setNonteachexp(String nonteachexp) {
        this.nonteachexp = nonteachexp;
    }

    public String getAge() {
        return this.age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public Date getConfirmdate() {
        return this.confirmdate;
    }

    public void setConfirmdate(Date confirmdate) {
        this.confirmdate = confirmdate;
    }

    public Character getApprove() {
        return this.approve;
    }

    public void setApprove(Character approve) {
        this.approve = approve;
    }

    public Character getDutyRequired() {
        return this.dutyRequired;
    }

    public void setDutyRequired(Character dutyRequired) {
        this.dutyRequired = dutyRequired;
    }

    public Character getPunchingrequired() {
        return this.punchingrequired;
    }

    public void setPunchingrequired(Character punchingrequired) {
        this.punchingrequired = punchingrequired;
    }

    public String getUanNo() {
        return this.uanNo;
    }

    public void setUanNo(String uanNo) {
        this.uanNo = uanNo;
    }

    public String getCareOf() {
        return this.careOf;
    }

    public void setCareOf(String careOf) {
        this.careOf = careOf;
    }

    public String getElectionId() {
        return this.electionId;
    }

    public void setElectionId(String electionId) {
        this.electionId = electionId;
    }

    public String getUan() {
        return this.uan;
    }

    public void setUan(String uan) {
        this.uan = uan;
    }

    public String getAadharno() {
        return this.aadharno;
    }

    public void setAadharno(String aadharno) {
        this.aadharno = aadharno;
    }

    public byte[] getImage() {
        return image;
    }

    public void setImage(byte[] image) {
        this.image = image;
    }



    public Character getResigned() {
        return this.resigned;
    }

    public void setResigned(Character resigned) {
        this.resigned = resigned;
    }

    public Character getVerified() {
        return this.verified;
    }

    public void setVerified(Character verified) {
        this.verified = verified;
    }

    public String getReferencestaffid() {
        return this.referencestaffid;
    }

    public void setReferencestaffid(String referencestaffid) {
        this.referencestaffid = referencestaffid;
    }

    public Character getStipend() {
        return this.stipend;
    }

    public void setStipend(Character stipend) {
        this.stipend = stipend;
    }

    public Character getVisiting() {
        return this.visiting;
    }

    public void setVisiting(Character visiting) {
        this.visiting = visiting;
    }

    public Character getInchargeDept() {
        return this.inchargeDept;
    }

    public void setInchargeDept(Character inchargeDept) {
        this.inchargeDept = inchargeDept;
    }

    public String getCollegeid() {
        return this.collegeid;
    }

    public void setCollegeid(String collegeid) {
        this.collegeid = collegeid;
    }

    public String getAcademicYear() {
        return this.academicYear;
    }

    public void setAcademicYear(String academicYear) {
        this.academicYear = academicYear;
    }

    public String getEnteredby() {
        return this.enteredby;
    }

    public void setEnteredby(String enteredby) {
        this.enteredby = enteredby;
    }

    public Date getEntereddate() {
        return this.entereddate;
    }

    public void setEntereddate(Date entereddate) {
        this.entereddate = entereddate;
    }

    public String getLastModifiedBy() {
        return this.lastModifiedBy;
    }

    public void setLastModifiedBy(String lastModifiedBy) {
        this.lastModifiedBy = lastModifiedBy;
    }

    public Date getLastModifiedDate() {
        return this.lastModifiedDate;
    }

    public void setLastModifiedDate(Date lastModifiedDate) {
        this.lastModifiedDate = lastModifiedDate;
    }

    public String getCaste() {
        return caste;
    }

    public void setCaste(String caste) {
        this.caste = caste;
    }

    public String getCastename() {
        return castename;
    }

    public void setCastename(String castename) {
        this.castename = castename;
    }

    public String getReligion() {
        return religion;
    }

    public void setReligion(String religion) {
        this.religion = religion;
    }

    public String getHandicap() {
        return handicap;
    }

    public void setHandicap(String handicap) {
        this.handicap = handicap;
    }

    public String getPermHouseNoName() {
        return permHouseNoName;
    }

    public void setPermHouseNoName(String permHouseNoName) {
        this.permHouseNoName = permHouseNoName;
    }

    public String getPermPost() {
        return permPost;
    }

    public void setPermPost(String permPost) {
        this.permPost = permPost;
    }

    public String getPermCity() {
        return permCity;
    }

    public void setPermCity(String permCity) {
        this.permCity = permCity;
    }

    public String getPermDistid() {
        return permDistid;
    }

    public void setPermDistid(String permDistid) {
        this.permDistid = permDistid;
    }

    public String getPermStateid() {
        return permStateid;
    }

    public void setPermStateid(String permStateid) {
        this.permStateid = permStateid;
    }

    public String getPermCountryid() {
        return permCountryid;
    }

    public void setPermCountryid(String permCountryid) {
        this.permCountryid = permCountryid;
    }

    public String getPermEmail() {
        return permEmail;
    }

    public void setPermEmail(String permEmail) {
        this.permEmail = permEmail;
    }

    public String getPermPin() {
        return permPin;
    }

    public void setPermPin(String permPin) {
        this.permPin = permPin;
    }

    public Character getHod() {
        return hod;
    }

    public void setHod(Character hod) {
        this.hod = hod;
    }

}
