package com.utils.map;
// Generated 30 Dec, 2016 1:24:09 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Studentinyear generated by hbm2java
 */
public class Studentinyear  implements java.io.Serializable {


     private String id;
     private String collegeid;
     private String admissionNo;
     private String activeyear;
     private String semesterId;
     private Character promoted;
     private Character active;
     private String courseid;
     private Character hostelReq;
     private Character messReq;
     private Character transportReq;
     private String enteredby;
     private Date entereddt;

    public Studentinyear() {
    }

	
    public Studentinyear(String id) {
        this.id = id;
    }
    public Studentinyear(String id, String collegeid, String admissionNo, String activeyear, String semesterId, Character promoted, Character active, String courseid, Character hostelReq, Character messReq, Character transportReq, String enteredby, Date entereddt) {
       this.id = id;
       this.collegeid = collegeid;
       this.admissionNo = admissionNo;
       this.activeyear = activeyear;
       this.semesterId = semesterId;
       this.promoted = promoted;
       this.active = active;
       this.courseid = courseid;
       this.hostelReq = hostelReq;
       this.messReq = messReq;
       this.transportReq = transportReq;
       this.enteredby = enteredby;
       this.entereddt = entereddt;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getCollegeid() {
        return this.collegeid;
    }
    
    public void setCollegeid(String collegeid) {
        this.collegeid = collegeid;
    }
    public String getAdmissionNo() {
        return this.admissionNo;
    }
    
    public void setAdmissionNo(String admissionNo) {
        this.admissionNo = admissionNo;
    }
    public String getActiveyear() {
        return this.activeyear;
    }
    
    public void setActiveyear(String activeyear) {
        this.activeyear = activeyear;
    }
    public String getSemesterId() {
        return this.semesterId;
    }
    
    public void setSemesterId(String semesterId) {
        this.semesterId = semesterId;
    }
    public Character getPromoted() {
        return this.promoted;
    }
    
    public void setPromoted(Character promoted) {
        this.promoted = promoted;
    }
    public Character getActive() {
        return this.active;
    }
    
    public void setActive(Character active) {
        this.active = active;
    }
    public String getCourseid() {
        return this.courseid;
    }
    
    public void setCourseid(String courseid) {
        this.courseid = courseid;
    }
    public Character getHostelReq() {
        return this.hostelReq;
    }
    
    public void setHostelReq(Character hostelReq) {
        this.hostelReq = hostelReq;
    }
    public Character getMessReq() {
        return this.messReq;
    }
    
    public void setMessReq(Character messReq) {
        this.messReq = messReq;
    }
    public Character getTransportReq() {
        return this.transportReq;
    }
    
    public void setTransportReq(Character transportReq) {
        this.transportReq = transportReq;
    }
    public String getEnteredby() {
        return this.enteredby;
    }
    
    public void setEnteredby(String enteredby) {
        this.enteredby = enteredby;
    }
    public Date getEntereddt() {
        return this.entereddt;
    }
    
    public void setEntereddt(Date entereddt) {
        this.entereddt = entereddt;
    }




}


