package com.utils.map;
// Generated 30 Dec, 2016 1:24:09 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Usermaster generated by hbm2java
 */
public class Usermaster  implements java.io.Serializable {


     private long id;
     private String username;
     private String password;
     private String staffid;
     private String roleid;
     private String collegeid;
     private Character active;
     private String loginmobileno;
     private Date createdDt;
     private String createdby;

    public Usermaster() {
    }

	
    public Usermaster(long id) {
        this.id = id;
    }
    public Usermaster(long id, String username, String password, String staffid, String roleid, String collegeid, Character active, String loginmobileno, Date createdDt, String createdby) {
       this.id = id;
       this.username = username;
       this.password = password;
       this.staffid = staffid;
       this.roleid = roleid;
       this.collegeid = collegeid;
       this.active = active;
       this.loginmobileno = loginmobileno;
       this.createdDt = createdDt;
       this.createdby = createdby;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getStaffid() {
        return this.staffid;
    }
    
    public void setStaffid(String staffid) {
        this.staffid = staffid;
    }
    public String getRoleid() {
        return this.roleid;
    }
    
    public void setRoleid(String roleid) {
        this.roleid = roleid;
    }
    public String getCollegeid() {
        return this.collegeid;
    }
    
    public void setCollegeid(String collegeid) {
        this.collegeid = collegeid;
    }
    public Character getActive() {
        return this.active;
    }
    
    public void setActive(Character active) {
        this.active = active;
    }
    public String getLoginmobileno() {
        return this.loginmobileno;
    }
    
    public void setLoginmobileno(String loginmobileno) {
        this.loginmobileno = loginmobileno;
    }
    public Date getCreatedDt() {
        return this.createdDt;
    }
    
    public void setCreatedDt(Date createdDt) {
        this.createdDt = createdDt;
    }
    public String getCreatedby() {
        return this.createdby;
    }
    
    public void setCreatedby(String createdby) {
        this.createdby = createdby;
    }




}


