package com.utils.map;
// Generated 30 Dec, 2016 1:24:09 PM by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * UserRolePrevilege generated by hbm2java
 */
public class UserRolePrevilege  implements java.io.Serializable {


     private String id;
     private String roleId;
     private String menuId;
     private String submenuId;
     private String menuOrder;
     private Character active;
     private String enteredBy;
     private Date entereddate;

    public UserRolePrevilege() {
    }

	
    public UserRolePrevilege(String id, String roleId, String menuId, String submenuId) {
        this.id = id;
        this.roleId = roleId;
        this.menuId = menuId;
        this.submenuId = submenuId;
    }
    public UserRolePrevilege(String id, String roleId, String menuId, String submenuId, String menuOrder, Character active, String enteredBy, Date entereddate) {
       this.id = id;
       this.roleId = roleId;
       this.menuId = menuId;
       this.submenuId = submenuId;
       this.menuOrder = menuOrder;
       this.active = active;
       this.enteredBy = enteredBy;
       this.entereddate = entereddate;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(String roleId) {
        this.roleId = roleId;
    }
    public String getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(String menuId) {
        this.menuId = menuId;
    }
    public String getSubmenuId() {
        return this.submenuId;
    }
    
    public void setSubmenuId(String submenuId) {
        this.submenuId = submenuId;
    }
    public String getMenuOrder() {
        return this.menuOrder;
    }
    
    public void setMenuOrder(String menuOrder) {
        this.menuOrder = menuOrder;
    }
    public Character getActive() {
        return this.active;
    }
    
    public void setActive(Character active) {
        this.active = active;
    }
    public String getEnteredBy() {
        return this.enteredBy;
    }
    
    public void setEnteredBy(String enteredBy) {
        this.enteredBy = enteredBy;
    }
    public Date getEntereddate() {
        return this.entereddate;
    }
    
    public void setEntereddate(Date entereddate) {
        this.entereddate = entereddate;
    }




}


