package com.utils.map;
// Generated 30 Dec, 2016 1:24:09 PM by Hibernate Tools 3.6.0



/**
 * Userrolemaster generated by hbm2java
 */
public class Userrolemaster  implements java.io.Serializable {


     private String id;
     private String rolename;
     private String remarks;

    public Userrolemaster() {
    }

	
    public Userrolemaster(String id) {
        this.id = id;
    }
    public Userrolemaster(String id, String rolename, String remarks) {
       this.id = id;
       this.rolename = rolename;
       this.remarks = remarks;
    }
   
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }
    public String getRolename() {
        return this.rolename;
    }
    
    public void setRolename(String rolename) {
        this.rolename = rolename;
    }
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }




}


